name-template: "v{{NEXT}} Draft"
tag-template: "v{{NEXT}}"
categories:
  - title: "🚀 New Features"
    labels:
      - "feat"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
  - title: "🔧 Improvements"
    labels:
      - "improvement"
template: |
  ## What's Changed
  $CHANGES

  ## Contributors
  $CONTRIBUTORS
change-template: "- $TITLE by @$AUTHOR in #$NUMBER"
no-changes-template: "* No changes"
version-resolver:
  major:
    labels:
      - "breaking-change"
  minor:
    labels:
      - "feat"
  patch:
    labels:
      - "fix"
prerelease: false
