name-template: 'v$NEXT_RELEASE_VERSION'
tag-template: 'v$NEXT_RELEASE_VERSION'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

template: |
  ## $NAME
  $CHANGES
  ### Version: $NEXT_RELEASE_VERSION

categories:
  - title: 'New Features'
    labels: ['feat']
  - title: 'Bug Fixes'
    labels: ['fix']
  - title: 'Improvements'
    labels: ['improvement']

versioning:
  - tag: 'v1.0.0'  # Start from version v1.0.0

next-version-template: 'v$MAJOR.$MINOR.$PATCH'

bump-minor-on:
  - 'feat'  # Increment minor version for new features

bump-patch-on:
  - 'fix'  # Increment patch version for bug fixes

bump-major-on:
  - 'breaking-change'  # Increment major version for breaking changes
