name: Release Drafter

on:
  push:
    branches:
      - main  # Trigger the action when a commit is pushed to the main branch

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkout the code from the repository

      - name: Set up Node.js for Release Drafter
        uses: actions/setup-node@v3  # Use the latest version of setup-node
        with:
          node-version: '20'  # Use Node.js 18 (or change to '20' for Node.js 20)

      - name: Generate Release Notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml  # Use the configuration file we created
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Provide GitHub token for access
