name: Release Drafter Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

permissions:
  contents: write  # Allows access to update content

jobs:
  update_release_drafter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml  # Your configuration file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Auth token for GitHub access

      # GitHub Tagging is handled automatically when a new tag is pushed
      - name: Push Release Drafter Tag
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

